// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using AutomationTest;

[TestFixture]
public class AddNewProductTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp(int type, string adminUserName, string adminPwd)
    {
        if (type == 0)
        {
            driver = new ChromeDriver(@"\", new ChromeOptions(), TimeSpan.FromMinutes(5)); // Chrome
        }
        else
        {
            driver = new FirefoxDriver(@"\", new FirefoxOptions(), TimeSpan.FromMinutes(5)); // Firefox
        }
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
        driver.Navigate().GoToUrl("https://stark-bastion-85279.herokuapp.com/admin-login.html"); // Login
        driver.Manage().Window.Size = new System.Drawing.Size(1400, 800);
        driver.FindElement(By.Name("email")).Click();
        driver.FindElement(By.Name("email")).SendKeys(adminUserName);
        driver.FindElement(By.Name("password")).Click();
        driver.FindElement(By.Name("password")).SendKeys(adminPwd);
        driver.FindElement(By.CssSelector(".btn.btn-ctl-bt")).Click();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void addNewProduct(Item item)
    {
        // Them san pham
        driver.FindElement(By.CssSelector("li:nth-child(3) .mini-click-non")).Click();
        driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(1);
        driver.FindElement(By.XPath("//*[@id='menu1']/li[3]/ul/li[6]/a")).Click();
        driver.FindElement(By.Name("stallId")).Click();
        {
            var dropdown = driver.FindElement(By.Name("stallId"));
            dropdown.FindElement(By.XPath("//option[. = '" + item.stall + "']")).Click();
        }
        driver.FindElement(By.Name("stallId")).Click();
        driver.FindElement(By.Name("brandId")).Click();
        {
            var dropdown = driver.FindElement(By.Name("brandId"));
            dropdown.FindElement(By.XPath("//option[. = '" + item.brand + "']")).Click();
        }
        driver.FindElement(By.Name("brandId")).Click();
        driver.FindElement(By.Name("name")).SendKeys(item.name);
        driver.FindElement(By.Name("oldPrice")).SendKeys(item.oldPrice);
        driver.FindElement(By.Name("price")).SendKeys(item.price);
        driver.FindElement(By.Name("qtyInStock")).SendKeys(item.stock);
        driver.FindElement(By.CssSelector(".input-group:nth-child(4) > .form-control")).SendKeys(item.description);
        driver.FindElement(By.CssSelector("#add-form .col-lg-6:nth-child(1)")).Click();
        driver.FindElement(By.XPath("//*[@id='add-form']/div[1]/div[1]/div/div[4]/input")).SendKeys(item.file);
        driver.FindElement(By.CssSelector(".btn-ctl-bt")).Click();
        Assert.That(driver.FindElement(By.CssSelector(".alert.alert-success")).Text, Is.EqualTo("Inserted successful :)"));
    }
}
